### ISSUE TITLE
Processing Kraken output with gb_taxonomy_tools

### ISSUE THREAD

**Issue by nekrut** [spond/gb_taxonomy_tools#1]
## Kraken output

[Kraken](https://ccb.jhu.edu/software/kraken/) classifies reads against sequence databases producing the following output (see [this link](http://www.bx.psu.edu/~anton/share/misc/kraken-example.txt) for a larger dataset):

``` text
C   M02286:29:000000000-AA53D:1:1105:19680:16914    1   483 Q:1
C   M02286:29:000000000-AA53D:1:1114:23595:17370    48479   477 Q:1
```

here, the second column (e.g., `M02286:29:000000000-AA53D:1:1105:19680:16914`) contains sequencing read names, the third (e.g., `1` and `48479`) are [NCBI taxonomy ids](http://www.ncbi.nlm.nih.gov/taxonomy), and the fourth (`483` and `477`) are alignment lengths. 
## What is the problem?

The current version of the `taxonomy-reader` ingests input datasets consisting of three columns including `gid`, `taxid`, and `count` triplets. It will not work on the Kraken dataset shown above (or [here](http://www.bx.psu.edu/~anton/share/misc/kraken-example.txt)) even if trimmed using `cut -f2,3,4` as it has some kind of a problem with the read ids.
## How should it work?

Ideally I would like to use three columns containing `read id`, `NCBI TaxId`, and `align length` to `taxonomy-reader` and have it output the `read id`, `NCBI TaxId`, and `align length` followed by full 22 field taxonomy list. That's it. 
### Actually,

even more generically, given any `value`, `taxId` pair output `value`, `taxId` followed by 22 taxonomy fields.

**Comment by spond** [comment]
Hi Anton,

Try the latest commit (I'll test and tag it off as a version). I have modified `taxonomy-reader` to take the third optional argument, which is the 0-based index of the field in the input stream lines where `taxid` lives. The default behavior now is to read the entire input line (can be more than 3 fields), split into tabs, and echo the entire input line to the output followed by the 22-field taxonomy dump.

So you should be able to run 

```
cat data/test/kraken.txt | ./taxonomy-reader names.dmp nodes.dmp 2
```

to get the output which looks like 

```
C   M02286:29:000000000-AA53D:1:1114:23595:17370    48479   477 Q:1 root    Bacteria    n   n   n   n   n   n   n   n   n   n   n   n
C   M02286:29:000000000-AA53D:1:1104:21103:22897    2   466 Q:1 root    Bacteria    n   n   n   n   n   n   n   n   n   n   n   n
C   M02286:29:000000000-AA53D:1:1116:7859:10478 77133   466 Q:1 root    Bacteria    n   n   n   n   n   n   n   n   n   n   n   uncultured bacterium    n   

...
```

Sergei

**Comment by nekrut** [comment]
perfect, thanks!

**Comment by spond** [comment]
Hi Anton,

Please use release 1.0.0

Sergei
